#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit"

# merging=$(git rev-parse -q --verify MERGE_HEAD)

# if [[ -z $merging ]]; then

#     pylint --help > /dev/null || { echo "\033[0;33m Pylint not found\033[0m"; exit 0; }

#     fileList=$(git diff --diff-filter=d --cached --name-only)
#     pyFileList=$(echo "$fileList" | grep -E '\.(py)$')

#     if [ ${#pyFileList} -gt 0 ]; then
#         if ! pylint ${pyFileList[*]} ; then
#             echo "\033[0;33m Pylint failed! \033[0m"
#             exit 1
#         fi
#     fi

# fi
